import image1 from '../assets/showcase1.jpg';
import image2 from '../assets/showcase2.jpg';
import image3 from '../assets/showcase3.jpg';
import image4 from '../assets/showcase4.jpg';
import image5 from '../assets/showcase5.jpg';
import image6 from '../assets/showcase6.jpg';
import image7 from '../assets/showcase7.jpg';
import image8 from '../assets/showcase8.jpg';
import image9 from '../assets/showcase9.jpg';
import image10 from '../assets/showcase10.jpg';
import image11 from '../assets/showcase11.jpg';
import image12 from '../assets/showcase12.jpg';
import image13 from '../assets/showcase13.jpg';
import image14 from '../assets/showcase14.jpg';
import image15 from '../assets/showcase15.jpg';
import image16 from '../assets/showcase16.jpg';
import image17 from '../assets/showcase17.jpg';
import image18 from '../assets/showcase18.jpg';
import image19 from '../assets/showcase19.jpg';
import image20 from '../assets/showcase20.jpg';
import image21 from '../assets/showcase21.jpg';
import image22 from '../assets/showcase22.jpg';
import image23 from '../assets/showcase23.jpg';
import image24 from '../assets/showcase24.jpg';
import image25 from '../assets/showcase25.jpg';


export const HotelDetail =[
    {
        id: 1,
        image: image1,
        title: 'Atliq Grands',
        desc: 'Escape to our luxurious resort and spa, nestled in the heart of breathtaking natural surroundings. Indulge in world-class amenities, rejuvenating spa treatments, and exquisite dining experiences. Experience the ultimate in relaxation and serenity at our resort.',

      },
      {
        id: 2,
        image: image2,
        title: 'Atliq Exotica',
        desc: 'Discover the charm of our seaside boutique hotel, located steps away from pristine sandy beaches. Immerse yourself in the tranquil coastal ambiance and enjoy breathtaking ocean views from our stylishly designed rooms. Experience coastal living at its finest.',

      },
      {
        id: 3,
        image: image3,
        title: 'Atliq City',
        desc: 'Unwind in our cozy mountain retreat lodge, surrounded by stunning peaks and lush forests. Experience the beauty of nature with hiking trails, mountain biking, and winter sports activities. Relax by the fireplace in our rustic yet elegant accommodations.',
      },
      {
        id: 4,
        image: image4,
        title: 'Atliq Blu',
        desc: 'Immerse yourself in the vibrant city life at our urban chic boutique hotel. Located in the heart of the bustling metropolis, our hotel offers stylish rooms, modern amenities, and easy access to shopping, dining, and entertainment venues. Experience the urban charm and sophistication.',

      },
      {
        id: 5,
        image: image5,
        title: 'Atliq Bay',
        desc: 'Step back in time at our historic inn and spa, where classic elegance meets modern comfort. Explore the rich history of the area and relax in our luxurious spa facilities. Indulge in gourmet dining and experience the timeless charm of our meticulously restored accommodations.',

      },
      {
        id: 6,
        image: image6,
        title: 'Atliq Palace',
        desc: 'Escape to our tropical paradise resort, located on a pristine island with white sandy beaches and crystal-clear turquoise waters. Immerse yourself in the tropical oasis with palm trees, exotic wildlife, and a range of water activities. Experience paradise like never before.',

      },
]


export const HotelRoomDetail = [
  {
    id: 1,
    pid: 16558,
    name: "Atliq Grands",
    category: "Luxury",
    city: "Delhi",
    images: image1,
    description: "Luxury Redefined: Experience Opulence Like Never Before",
    extras: ['Complimentary refreshments such as bottled water or coffee/tea making facilities in rooms', '24-hour room service offering a variety of dining options', 'High-speed internet access, both wired and wireless, for seamless connectivity', 'Pet-friendly accommodations with amenities for furry guests', 'Outdoor swimming pool with sun loungers and poolside service'],
    rt1_count: 19,
    rt2_count: 22,
    rt3_count: 8,
    rt4_count: 3,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
 {
    id: 2,
    pid: 16559,
    name: "Atliq Exotica",
    category: "Luxury",
    city: "Mumbai",
    images: image2,
    description: "Seaside Serenity: Your Escape to Coastal Tranquility",
    extras: ['Soft and absorbent bath towels for comfort after showering', 'Personalized concierge services for restaurant reservations and local recommendations', 'Spacious work desks and ergonomic chairs for business travelers', 'Full-sized toiletries with a selection of high-quality, pH-balanced products', 'Environmental sustainability initiatives such as energy-efficient lighting and recycling programs'],
    rt1_count: 30,
    rt2_count: 41,
    rt3_count: 32,
    rt4_count: 18,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
 {
    id: 3,
    pid: 16560,
    name: "Atliq City",
    category: "Business",
    city: "Delhi",
    images: image3,
    description: "Urban Oasis: Discover Chic Comfort in the Heart of the City",
    extras: ['Access to nearby golf courses or exclusive golf packages', 'Yoga and meditation classes for relaxation and fitness', 'In-room entertainment options such as flat-screen TVs with cable/satellite channels', "Comfortable beds with hypoallergenic pillows and mattresses to ensure a restful night's sleep", 'Multilingual staff for international guests'],
    rt1_count: 24,
    rt2_count: 34,
    rt3_count: 20,
    rt4_count: 7,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
 {
    id: 4,
    pid: 16561,
    name: "Atliq Blu",
    category: "Luxury",
    city: "Delhi",
    images: image4,
    description: "Historic Elegance Meets Modern Comfort",
    extras: ['Well-equipped fitness center with cardio machines and free weights', 'On-site dining options including gourmet restaurants and casual cafes', 'Meeting rooms and conference facilities with audiovisual equipment', 'Convenient USB charging ports and power outlets bedside', 'Gift shop offering souvenirs and travel essentials'],
    rt1_count: 18,
    rt2_count: 24,
    rt3_count: 21,
    rt4_count: 10,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
 {
    id: 5,
    pid: 16562,
    name: "Atliq Bay",
    category: "Luxury",
    city: "Delhi",
    images: image5,
    description: "Where Every Sunset is Magical: Unwind in Paradise",
    extras: ['Outdoor terrace or garden areas for relaxation and scenic views', '24-hour room service offering a variety of dining options', 'Business center with computers, printers, and fax machines', 'Laundry and dry cleaning services with same-day turnaround', 'Art and decor reflecting local culture and heritage'],
    rt1_count: 31,
    rt2_count: 43,
    rt3_count: 18,
    rt4_count: 6,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
 {
    id: 6,
    pid: 16563,
    name: "Atliq Palace",
    category: "Business",
    city: "Delhi",
    images: image6,
    description: "Boutique Bliss: Personalized Luxury Awaits",
    extras: ['On-site bar and lounge areas for socializing and relaxation', "Family-friendly amenities such as kids' clubs and babysitting services", "Comfortable beds with hypoallergenic pillows and mattresses to ensure a restful night's sleep", 'Airport shuttle service for seamless transportation to and from the hotel', 'Car rental desk for exploring the local area at your own pace'],
    rt1_count: 41,
    rt2_count: 38,
    rt3_count: 20,
    rt4_count: 18,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
 {
    id: 7,
    pid: 17558,
    name: "Atliq Grands",
    category: "Luxury",
    city: "Mumbai",
    images: image7,
    description: "Savor the Essence of Your Destination: Stay, Explore, Indulge",
    extras: ['Spa facilities offering massages, facials, and wellness treatments', 'In-room massage and spa treatments for ultimate relaxation', 'Exclusive club lounge access for premium guests', 'Turndown service with chocolates or mints provided in the evenings', 'Cultural and recreational activities organized by the hotel'],
    rt1_count: 19,
    rt2_count: 50,
    rt3_count: 27,
    rt4_count: 6,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
 {
    id: 8,
    pid: 17559,
    name: "Atliq Exotica",
    category: "Luxury",
    city: "Mumbai",
    images: image8,
    description: "Unravel the Charms of Your Destination: Your Perfect Retreat",
    extras: ['Valet parking and convenient on-site parking facilities', 'Ticket booking services for local attractions and events', 'Express check-in and check-out services for convenience', 'Soundproof rooms for enhanced privacy and noise reduction', 'Outdoor adventure packages including hiking, biking, or water sports'],
    rt1_count: 32,
    rt2_count: 39,
    rt3_count: 16,
    rt4_count: 14,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
 {
    id: 9,
    pid: 17560,
    name: "Atliq City",
    category: "Business",
    city: "Mumbai",
    images: image9,
    description: "Adventure Awaits: Your Basecamp for Exploration",
    extras: ['Dining options including gourmet restaurants and casual cafes', 'Art and decor reflecting local culture and heritage', '24-hour room service offering a variety of dining options', 'High-speed internet access, both wired and wireless, for seamless connectivity', 'Pet-friendly accommodations with amenities for furry guests'],
    rt1_count: 40,
    rt2_count: 45,
    rt3_count: 25,
    rt4_count: 13,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
 {
    id: 10,
    pid: 17561,
    name: "Atliq Blu",
    category: "Luxury",
    city: "Mumbai",
    images: image10,
    description: "Eco-Luxury: Embrace Sustainability in Style",
    extras: ['Soft and absorbent bath towels for comfort after showering', '24-hour room service offering a variety of dining options', 'Full-sized toiletries with a selection of high-quality, pH-balanced products', "Comfortable beds with hypoallergenic pillows and mattresses to ensure a restful night's sleep", 'Business center with computers, printers, and fax machines'],
    rt1_count: 26,
    rt2_count: 36,
    rt3_count: 19,
    rt4_count: 4,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
 {
    id: 11,
    pid: 17562,
    name: "Atliq Bay",
    category: "Luxury",
    city: "Mumbai",
    images: image11,
    description: "Timeless Sophistication: Unveiling the Art of Hospitality",
    extras: ['Outdoor swimming pool with sun loungers and poolside service', 'Environmental sustainability initiatives such as energy-efficient lighting and recycling programs', 'Access to nearby golf courses or exclusive golf packages', '24-hour room service offering a variety of dining options', 'In-room entertainment options such as flat-screen TVs with cable/satellite channels'],
    rt1_count: 20,
    rt2_count: 30,
    rt3_count: 27,
    rt4_count: 6,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
 {
    id: 12,
    pid: 17563,
    name: "Atliq Palace",
    category: "Business",
    city: "Mumbai",
    images: image12,
    description: "Culinary Journey: Delight Your Senses, Stay in Comfort",
    extras: ['Well-equipped fitness center with cardio machines and free weights', 'Personalized concierge services for restaurant reservations and local recommendations', 'Spacious work desks and ergonomic chairs for business travelers', 'Soft and absorbent bath towels for comfort after showering', 'Pet-friendly accommodations with amenities for furry guests'],
    rt1_count: 25,
    rt2_count: 44,
    rt3_count: 16,
    rt4_count: 19,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
 {
    id: 13,
    pid: 17564,
    name: "Atliq Seasons",
    category: "Business",
    city: "Mumbai",
    images: image13,
    description: "Tranquil Hideaway: Rejuvenate Your Mind, Body, and Soul",
    extras: ["Comfortable beds with hypoallergenic pillows and mattresses to ensure a restful night's sleep", 'Multilingual staff for international guests', 'Yoga and meditation classes for relaxation and fitness', 'In-room entertainment options such as flat-screen TVs with cable/satellite channels', 'Full-sized toiletries with a selection of high-quality, pH-balanced products'],
    rt1_count: 16,
    rt2_count: 40,
    rt3_count: 24,
    rt4_count: 17,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
 {
    id: 14,
    pid: 18558,
    name: "Atliq Grands",
    category: "Luxury",
    city: "Hyderabad",
    images: image14,
    description: "Artisanal Luxury: Curated Experiences for the Discerning Traveler",
    extras: ['Gift shop offering souvenirs and travel essentials', 'Business center with computers, printers, and fax machines', 'On-site dining options including gourmet restaurants and casual cafes', 'Well-equipped fitness center with cardio machines and free weights', 'Meeting rooms and conference facilities with audiovisual equipment'],
    rt1_count: 15,
    rt2_count: 30,
    rt3_count: 26,
    rt4_count: 20,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
 {
    id: 15,
    pid: 18559,
    name: "Atliq Exotica",
    category: "Luxury",
    city: "Hyderabad",
    images: image15,
    description: "Seamless Harmony of Nature and Luxury",
    extras: ['Outdoor terrace or garden areas for relaxation and scenic views', '24-hour room service offering a variety of dining options', 'Business center with computers, printers, and fax machines', 'Laundry and dry cleaning services with same-day turnaround', 'Art and decor reflecting local culture and heritage'],
    rt1_count: 42,
    rt2_count: 44,
    rt3_count: 23,
    rt4_count: 19,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
 {
    id: 16,
    pid: 18560,
    name: "Atliq City",
    category: "Business",
    city: "Hyderabad",
    images: image16,
    description: "Where Dreams Meet Reality: Your Ultimate Getaway",
    extras: ['On-site bar and lounge areas for socializing and relaxation', "Family-friendly amenities such as kids' clubs and babysitting services", "Comfortable beds with hypoallergenic pillows and mattresses to ensure a restful night's sleep", 'Airport shuttle service for seamless transportation to and from the hotel', 'Car rental desk for exploring the local area at your own pace'],
    rt1_count: 30,
    rt2_count: 40,
    rt3_count: 24,
    rt4_count: 15,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
 {
    id: 17,
    pid: 18561,
    name: "Atliq Blu",
    category: "Luxury",
    city: "Hyderabad",
    images: image17,
    description: "Escape to Your Destination's Best Kept Secret",
    extras: ['Spa facilities offering massages, facials, and wellness treatments', 'In-room massage and spa treatments for ultimate relaxation', 'Exclusive club lounge access for premium guests', 'Turndown service with chocolates or mints provided in the evenings', 'Cultural and recreational activities organized by the hotel'],
    rt1_count: 33,
    rt2_count: 40,
    rt3_count: 25,
    rt4_count: 9,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
 {
    id: 18,
    pid: 18562,
    name: "Atliq Bay",
    category: "Luxury",
    city: "Hyderabad",
    images: image18,
    description: "Embrace the Rhythms of Your Destination: Your Cultural Haven",
    extras: ['Valet parking and convenient on-site parking facilities', 'Ticket booking services for local attractions and events', 'Express check-in and check-out services for convenience', 'Soundproof rooms for enhanced privacy and noise reduction', 'Outdoor adventure packages including hiking, biking, or water sports'],
    rt1_count: 38,
    rt2_count: 34,
    rt3_count: 29,
    rt4_count: 20,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
 {
    id: 19,
    pid: 18563,
    name: "Atliq Palace",
    category: "Business",
    city: "Hyderabad",
    images: image19,
    description: "Discover Your Destination Through Our Eyes: Unforgettable Stays Await",
    extras: ['Dining options including gourmet restaurants and casual cafes', 'Art and decor reflecting local culture and heritage', '24-hour room service offering a variety of dining options', 'High-speed internet access, both wired and wireless, for seamless connectivity', 'Pet-friendly accommodations with amenities for furry guests'],
    rt1_count: 27,
    rt2_count: 29,
    rt3_count: 23,
    rt4_count: 18,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
 {
    id: 20,
    pid: 19558,
    name: "Atliq Grands",
    category: "Luxury",
    city: "Bangalore",
    images: image20,
    description: "Luxury with a Local Touch: Immerse Yourself in Authenticity",
    extras: ['Soft and absorbent bath towels for comfort after showering', '24-hour room service offering a variety of dining options', 'Full-sized toiletries with a selection of high-quality, pH-balanced products', "Comfortable beds with hypoallergenic pillows and mattresses to ensure a restful night's sleep", 'Business center with computers, printers, and fax machines'],
    rt1_count: 40,
    rt2_count: 39,
    rt3_count: 21,
    rt4_count: 7,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
 {
    id: 21,
    pid: 19559,
    name: "Atliq Exotica",
    category: "Luxury",
    city: "Bangalore",
    images: image21,
    description: "Indulge in Privacy and Panoramic Views",
    extras: ['Outdoor swimming pool with sun loungers and poolside service', 'Environmental sustainability initiatives such as energy-efficient lighting and recycling programs', 'Access to nearby golf courses or exclusive golf packages', '24-hour room service offering a variety of dining options', 'In-room entertainment options such as flat-screen TVs with cable/satellite channels'],
    rt1_count: 24,
    rt2_count: 41,
    rt3_count: 27,
    rt4_count: 3,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
 {
    id: 22,
    pid: 19560,
    name: "Atliq City",
    category: "Business",
    city: "Bangalore",
    images: image22,
    description: "Legendary Hospitality in the Heart of Your Destination",
    extras: ['Well-equipped fitness center with cardio machines and free weights', 'Personalized concierge services for restaurant reservations and local recommendations', 'Spacious work desks and ergonomic chairs for business travelers', 'Soft and absorbent bath towels for comfort after showering', 'Pet-friendly accommodations with amenities for furry guests'],
    rt1_count: 26,
    rt2_count: 38,
    rt3_count: 19,
    rt4_count: 16,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
 {
    id: 23,
    pid: 19561,
    name: "Atliq Blu",
    category: "Luxury",
    city: "Bangalore",
    images: image23,
    description: "Where Adventure Meets Relaxation: Your Perfect Balance",
    extras: ["Comfortable beds with hypoallergenic pillows and mattresses to ensure a restful night's sleep", 'Multilingual staff for international guests', 'Yoga and meditation classes for relaxation and fitness', 'In-room entertainment options such as flat-screen TVs with cable/satellite channels', 'Full-sized toiletries with a selection of high-quality, pH-balanced products'],
    rt1_count: 36,
    rt2_count: 45,
    rt3_count: 29,
    rt4_count: 7,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
 {
    id: 24,
    pid: 19562,
    name: "Atliq Bay",
    category: "Luxury",
    city: "Bangalore",
    images: image24,
    description: "The Essence of Tranquility: Your Sanctuary Awaits",
    extras: ['Gift shop offering souvenirs and travel essentials', 'Business center with computers, printers, and fax machines', 'On-site dining options including gourmet restaurants and casual cafes', 'Well-equipped fitness center with cardio machines and free weights', 'Meeting rooms and conference facilities with audiovisual equipment'],
    rt1_count: 30,
    rt2_count: 23,
    rt3_count: 29,
    rt4_count: 7,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
 {
    id: 25,
    pid: 19563,
    name: "Atliq Palace",
    category: "Luxury",
    city: "Bangalore",
    images: image25,
    description: "Unveiling Serenity: Retreat to Unmatched Comfort",
    extras: ['Outdoor terrace or garden areas for relaxation and scenic views', '24-hour room service offering a variety of dining options', 'Business center with computers, printers, and fax machines', 'Laundry and dry cleaning services with same-day turnaround', 'Art and decor reflecting local culture and heritage'],
    rt1_count: 30,
    rt2_count: 45,
    rt3_count: 29,
    rt4_count: 6,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
];
